ci(ci): 修改react-webpack.yml配置，修改阿里云ACR登录配置

diff --git a/.github/workflows/react-webpack.yml b/.github/workflows/react-webpack.yml
--- a/.github/workflows/react-webpack.yml
+++ b/.github/workflows/react-webpack.yml
@@ -77,7 +77,7 @@ jobs:
             # 登录阿里云 ACR
             # docker login -u $secrets.ALIYUN_ACR_USERNAME -p $secrets.ALIYUN_ACR_PASSWORD $secrets.ALIYUN_ACR_REGISTRY
             # 登录阿里云 ACR（使用 --password-stdin 避免交互式输入）
-            echo "${{ secrets.ALIYUN_ACR_PASSWORD }}" | docker login -u "${{ secrets.ALIYUN_ACR_USERNAME }}" --password-stdin "${{ secrets.ALIYUN_ACR_REGISTRY }}"
+            echo "${{ secrets.ALIYUN_ACR_PASSWORD }}" | docker login -u "${{ secrets.ALIYUN_ACR_USERNAME }}" --password-stdin "${{ secrets.ALIYUN_ACR_REGISTRY }}" && echo "Login successful" || echo "Login failed"
 
             # 创建 .env 文件
             echo "ALIYUN_REGISTRY=${{ secrets.ALIYUN_ACR_REGISTRY }}" > .env
